version = 1

test_patterns = [
  "**/test_*.py"
]

exclude_patterns = [
  "erpnext_ocr/patches/**",
  "*.min.js"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
